server:
  port: 8099

spring:
  data:
    mongodb:
      uri: mongodb+srv://allUser:allUser123456@conteinerdb.99ukk.mongodb.net/?retryWrites=true&w=majority
      database: ConteinerDB

  datasource:
     url: jdbc:mysql://localhost:3306/threego?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
     username: root
     password: 123456


  jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


